#!/usr/bin/env bash
set -euo pipefail

# Purpose:
#   Install convenience aliases/functions for faster daily Kubernetes lab operations.
#
# Important:
#   This script does NOT install Kubernetes, configure nodes, or change cluster state.
#   It only creates shell shortcuts and auto-loads them from ~/.bashrc.
#
# Safe behavior:
#   - idempotent (safe to re-run)
#   - writes only:
#       ~/.k8s-lab-shortcuts.sh
#       ~/.bashrc (adds one source line if missing)
#
SHORTCUT_FILE="${HOME}/.k8s-lab-shortcuts.sh"
BASHRC_FILE="${HOME}/.bashrc"
SOURCE_LINE='[ -f "$HOME/.k8s-lab-shortcuts.sh" ] && source "$HOME/.k8s-lab-shortcuts.sh"'

mkdir -p "$(dirname "$SHORTCUT_FILE")"

cat > "$SHORTCUT_FILE" <<'EOF'
# Kubernetes HA Lab shortcuts
# Generated by scripts/install-k8s-shortcuts.sh

alias k='kubectl'
alias kg='kubectl get'
alias kd='kubectl describe'
alias ka='kubectl apply -f'
alias kdel='kubectl delete'
alias kn='kubectl get nodes -o wide'
alias kpa='kubectl get pods -A -o wide'
alias ksys='kubectl get pods -n kube-system -o wide'
alias kcal='kubectl get pods -n calico-system -o wide'
alias kevents='kubectl get events -A --sort-by=.lastTimestamp | tail -n 120'
alias ksc='kubectl get storageclass'
alias kpvc='kubectl get pvc -A'

kgatus() { kubectl -n gatus-demo "$@"; }
kkuma() { kubectl -n uptime-kuma "$@"; }

khealth() {
  kubectl get nodes -o wide
  echo
  kubectl get pods -n kube-system -o wide
  echo
  kubectl get pods -n calico-system -o wide
}

kapi() {
  getent hosts api || true
  nc -vz api 6443 || true
  kubectl -n kube-system get cm kubeadm-config -o jsonpath='{.data.ClusterConfiguration}' | grep controlPlaneEndpoint || true
  kubectl config view --minify | grep server || true
}

kcordon() {
  if [ $# -ne 1 ]; then
    echo "Usage: kcordon <node>"
    return 1
  fi
  kubectl cordon "$1"
}

kdrain() {
  if [ $# -ne 1 ]; then
    echo "Usage: kdrain <node>"
    return 1
  fi
  kubectl drain "$1" --ignore-daemonsets --delete-emptydir-data --force
}

kuncordon() {
  if [ $# -ne 1 ]; then
    echo "Usage: kuncordon <node>"
    return 1
  fi
  kubectl uncordon "$1"
}

kwatchnodes() {
  watch -n 2 'kubectl get nodes -o wide'
}

kwatchall() {
  watch -n 2 'kubectl get nodes -o wide; echo; kubectl get pods -A -o wide'
}

kwatchkuma() {
  watch -n 2 'kubectl get nodes -o wide; echo; kubectl -n uptime-kuma get pods -o wide'
}

kwatchgatus() {
  watch -n 2 'kubectl get nodes -o wide; echo; kubectl -n gatus-demo get pods -o wide'
}

if command -v ssh >/dev/null 2>&1; then
  alias c01='ssh cp01'
  alias c02='ssh cp02'
  alias c03='ssh cp03'
  alias w01='ssh wk01'
  alias w02='ssh wk02'
  alias l01='ssh lb01'
  alias l02='ssh lb02'
fi

khelp() {
  cat <<'EOT'
Shortcuts loaded.

Core:
  kn             -> kubectl get nodes -o wide
  kpa            -> kubectl get pods -A -o wide
  ksys           -> kube-system pods
  kcal           -> calico-system pods
  kevents        -> recent cluster events
  ksc            -> storage classes
  kpvc           -> pvc list

Functions:
  khealth        -> nodes + kube-system + calico snapshot
  kapi           -> api endpoint and kubeconfig checks
  kcordon NODE   -> cordon node
  kdrain NODE    -> drain node
  kuncordon NODE -> uncordon node
  kwatchnodes    -> watch nodes
  kwatchall      -> watch nodes + all pods
  kwatchkuma     -> watch uptime-kuma namespace
  kwatchgatus    -> watch gatus-demo namespace
  kgatus ...     -> kubectl -n gatus-demo ...
  kkuma ...      -> kubectl -n uptime-kuma ...

SSH aliases (if hostnames resolve):
  c01 c02 c03 w01 w02 l01 l02
EOT
}
EOF

if [ ! -f "$BASHRC_FILE" ]; then
  touch "$BASHRC_FILE"
fi

if ! grep -Fq "$SOURCE_LINE" "$BASHRC_FILE"; then
  {
    echo
    echo "# Kubernetes HA lab shortcuts"
    echo "$SOURCE_LINE"
  } >> "$BASHRC_FILE"
fi

# shellcheck source=/dev/null
source "$SHORTCUT_FILE"

echo "Installed shortcuts to $SHORTCUT_FILE"
echo "Loaded in current shell. Run 'khelp' to view commands."
echo "To remove: delete $SHORTCUT_FILE and remove its source line from $BASHRC_FILE."
